### ISSUE TITLE
Missing Gifs

### ISSUE THREAD

**Issue by pltaylor** [kahanu/Security-Guard#1]
The following gifs referenced in the pagination.css are not in the images folder
images/pag_bg.gif
images/prev.gif
images/next.gif
images/go.gif

**Comment by kahanu** [comment]
pltaylor, nice catch. I just updated the github source code and updated the NuGet package.  King Wilder

**Comment by pltaylor** [comment]
thanks for fixing this so quickly.

**Comment by kahanu** [comment]
Perry, no problem.
