### ISSUE TITLE
Unscoped DOM calls in JavaScript could be a problem with customized layouts.

### ISSUE THREAD

**Issue by xnodeoncode** [kahanu/Security-Guard#10]
I am using SecurityGuard in one of my applications and for a consistent look and feel, I customized the _SecurityGuardLayoutPage.cshtml with the layout and styles that I wanted to use. Well viewing the roles in security, I found that every time that I selected a role in the drop-down list, my navigation would disappear. So I looked at the source code and found that in the Views\Roles\Index.cshtml, there is a client-side javascript method "OnGetUsersInRolesSuccess()" that has a call to:

$("li").remove();

This will remove all <li> items from the DOM instead of simply clearing the <ul> list that it was intended to clear. I think that a better approach would be the one I took where all calls are scoped to the ui elemented intended so that users can customize the pages / themes without impacting the client-side functionality.

I changed all un-scoped calls like the one above to:
/***********************************************
        \* Begin Get Users In Role Functions
        ***********************************************/

```
    // users-in-role-div
    // roles ul DOM element

    var usersInRoleDiv = $("#users-in-role-div");
    var ul = $("#users-in-role-div ul");
```

 function OnGetUsersInRoleSuccess(data) {
            //this call should be scoped
            //$("li").remove();
            ul.empty();

```
        if (data == "") {
            ul.append("<li>No user(s).</li>");
        } else {
            $.each(data, function (index, item) {
                ul.append("<li><a href=\"/SecurityGuard/Membership/Update/" + item + "\">" + item + "</a></li>");
            });
        }
    }
```

I would have requested a pull but I thought that this was an easy enough fix. Great work though...saves alot of time when it comes to managing users.

**Comment by kahanu** [comment]
@xnodeoncode - nice catch!  Yes I can easily fix this.  I'll try to get the fix pushed in the next day or so.  Thanks.

**Comment by kahanu** [comment]
@xnodeoncode - I've updated this bug and NuGet package.  Thanks again for finding this.
