### ISSUE TITLE
CreateUser action appears to not properly verify Password and ConfirmPassword match

### ISSUE THREAD

**Issue by SteveHiner** [kahanu/Security-Guard#12]
I noticed today that I could create a user even if I didn't match the passwords.  It appears it is checking it at some level because I was able to fix it by adding this to the top of MembershipController.CreateUser:
            if (model.Password != model.ConfirmPassword)
                return View(model);
I didn't have to set an error message because when it renders the view it puts in a message indicating that the passwords don't match.

Note: I am not using the latest version from NuGet. I customized it way too much to be able to update from NuGet.  Forgive me if this is something you've already fixed.  I checked the issue list and didn't see it in there.

**Comment by xnodeoncode** [comment]
nice catch...i sent a pull request to incorporate your fix into the main branch. I haven't analyzed the JSON method though, it may still need to be revised.

**Comment by kahanu** [comment]
@SteveHiner - This is not a bug!  Please check for me the model in the POST CreateUser method of the MembershipController.  It should look like this:

```
[HttpPost]
public virtual ActionResult CreateUser(viewModels.RegisterViewModel model)
```

That RegisterViewModel has the "Compare" attribute on the ConfirmPassword property.  This validates that the two values are correct.  I've tested this and it does work.

If you need to, you can just update your (or create) RegisterViewModel in the Models folder of the SecurityGuard Area to look like this and it should work.

```
public class RegisterViewModel
{
    [Required]
    [Display(Name = "User name")]
    public string UserName { get; set; }

    [Required]
    [DataType(DataType.EmailAddress)]
    [Display(Name = "Email address")]
    public string Email { get; set; }

    [Required]
    [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
    [DataType(DataType.Password)]
    [Display(Name = "Password")]
    public string Password { get; set; }

    [DataType(DataType.Password)]
    [Display(Name = "Confirm password")]
    [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
    public string ConfirmPassword { get; set; }

    [Display(Name = "Secret Question")]
    public string SecretQuestion { get; set; }

    [Display(Name = "Secret Answer")]
    public string SecretAnswer { get; set; }

    public bool Approve { get; set; }

    public bool RequireSecretQuestionAndAnswer { get; set; }
}
```

I understand your reservations about upgrading, but NuGet should not overwrite changed files.  If you want, you can copy your _SecurityGuardLayoutPage.cshtml to another location, and then do an upgrade and see if it overwrites this file.  If it does, then you can copy your original file back in.

Let me know if this works.

**Comment by kahanu** [comment]
@xnodeoncode - thanks for the quick response to Steve's issue, but the Compare attribute is the better way to go.  Let's see how that turns out.

**Comment by SteveHiner** [comment]
I am using the model as you built it and it does have the compare
attribute.  That's no doubt why it works with my slight modification, all I
had to do was return the the View and it added the error message about the
passwords not matching.  It appears that it will enter that POST and create
the user without doing the comparison.  Is that validation supposed to
happen before my Action is called?

I tried upgrading using NuGet a while back and it trashed my SecurityGuard
install to the degree that I had to scrub it and pull everything out of
source control.  Since then I've modified a lot more than the layout file.
I've added the ability to edit the user's profile properties (name,
address, etc.), added a password strength meter to the user creation and
editing, added a random password suggestion feature to user creation,
tweaked the role editing to not show roles that aren't interesting to the
user (working with an existing database, will eventually delete those
roles) and changed role editing so managers can't create admin level users
accounts.  I know it's best to limit who can create users to a single role
but for my client there are two roles that need to be able to do it.  It's
a private site so they have to manually create every user, that's a
manager's job but only admins can create managers or other admins.  I still
need to see if I can change the layout enough to make it look like the rest
of the site without seriously breaking other things.  I hated breaking
compatibility with the standard package but I needed features that weren't
present.

Steve

**Comment by kahanu** [comment]
@SteveHiner - Wow, yeah you've done a lot to modify this.  A lot of what you did sounds cool.

Regarding the POST of CreateUser, all attributes on the RegisterViewModel class are validated prior to the Action being called, this way you can check it inside the method with something like:

```
if(!ModelState.IsValid){
    // Do something
}
```

I'm not sure why it isn't validating.  I'll check it out more thoroughly when I have a moment, I'm in the middle of moving and my house is closing escrow Tuesday.

For most actions I don't return directly to the view, especially when an exception occurs since I want to follow the PRG pattern (POST/Redirect/Get).  I return the controller action, this way users cannot simply click Refresh and execute the last command.

Would you be interested in sending me your code?  Some of it sounds like it would fit into this for extra features nicely.  I still want it to remain as generally available and not too specific to any particular application, but some of your features might be nice to integrate.  Let me know.
