### ISSUE TITLE
2 viewmodels have ambiguous reference exception on  build

### ISSUE THREAD

**Issue by bdelaney** [kahanu/Security-Guard#15]
Clean MVC 4 project. Added SG via Nuget. Modifying according to Wiki.
Build Error:
'CompareAttribute' is an ambiguous reference between 'System.ComponentModel.DataAnnotations.CompareAttribute' and 'System.Web.Mvc.CompareAttribute'

Changed line 25 in RegisterViewModel
to: System.ComponentModel.DataAnnotations.Compare

and line 21 in ChangePasswordViewModel
to: System.ComponentModel.DataAnnotations.Compare

Clean build

Choice based on this StackOverflow
http://stackoverflow.com/q/10668948
 comment by Vinney K:

So, looking at the MSDN documentation and doing a literal comparison of the two classes, I noticed both classes are derived from System.ComponentModel.DataAnnotations.ValidationAttribute. In fact, the classes are almost exactly the same. The only notable difference is that the MVC version also implements IClientValidatable which adds the following properties:
•FormatPropertyForClientValidation - Formats the property for client validation by prepending an asterisk () and a dot.\* 
•GetClientValidationRules - Gets a list of compare-value client validation rules for the property using the specified model metadata and controller context.

As for which class you should you, if the model will be directly bound to a view, use the MVC version so that you can take advantage of the client-side validation. However, if you're using ViewModels, you can stick with the ComponentModel class and avoid the unnecessary overhead of the additional properties. Your call!

**Comment by kahanu** [comment]
I have encountered this once with MVC 4, but some other times not. I have to do more MVC 4 testing.  You're in the right direction to fix the issue.  I'll come up with a solid solution soon.  Thanks for the notice.

**Comment by kahanu** [comment]
I did create a couple test MVC 4 applications and did not encounter this issue.  Was there anything that you did that was not simply creating an MVC 4 application and installing SecurityGuard.MVC4 via NuGet?

**Comment by kahanu** [comment]
This has been updated in the latest release.  Version 1.0.6
