### ISSUE TITLE
SQLExpress connection?

### ISSUE THREAD

**Issue by bdelaney** [kahanu/Security-Guard#16]
In an  MVC4 clean project, Internet template, with initialized LocalDB membership database, SG treis to create a new SQLexpress instance and fails.
Any suggestions?

**Comment by kahanu** [comment]
@bdelaney - SG doesn't create databases, it simply makes a connection to the database in the connection string.  You need to make sure the connection string is what works.  Does that answer your question?

**Comment by bdelaney** [comment]
thanks for your quick response. I am going to look at this again today. It's a great piece of work and I'm glad you are making it MVC4 compatible. I also noted the addition of a google group so I will address future questions there.

For this one, well, I'm wondering where SQ gets its dbconnection string? The error I am getting when I attempt to use the logon page seems to call on sqlexpress, not localdb. My database is already initialized and I followed your instructions to the letter in the wiki page: 3. Setup
The debug run errors on line61 in SGAccountController (see error text below)

My dbconnection/db looks like this under VS2012 Server Explorer: http://imgur.com/1oijm
So, that shows I do have an actual membership database as created by default MVC4 membership logon.

The connection string is the default for a new MVC4 Internet project:
    <add name="DefaultConnection" connectionString="Data Source=(LocalDb)\v11.0;Initial Catalog=aspnet-MVCmembershipTest-20121003145156;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|\aspnet-MVCmembershipTest-20121003145156.mdf" providerName="System.Data.SqlClient" />

Here is the error displayed in browser:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

SQLExpress database file auto-creation error: 

The connection string specifies a local Sql Server Express instance using a database location within the application's App_Data directory. The provider attempted to automatically create the application services database because the provider determined that the database does not exist. The following configuration requirements are necessary to successfully check for existence of the application services database and automatically create the application services database:

**Comment by kahanu** [comment]
@bdelaney - I just created an MVC 4 application and installed SecurityGuard.Mvc4 and it built and ran without errors or problems.

I'll try to answer your questions:

-- Where SG gets the connection string - from the web.config/connectionStrings section.

I'm not clear on what this is: "My dbconnection/db looks like this under VS2012 Server Explorer: http://imgur.com/1oijm".  

Can you show me what your connection string looks like?

As long as you have a connection string in your web.config file that points to a working database, SecurityGuard will work.

**Comment by j-tee** [comment]
I have the most weird problem i could ever imagine. I have security guard working fine then i moved on to do something else a few weeks later i came back to my mvc4 app i discovered Security guard is using some database i cant locate in my application. The database i provided for managing users is still there. When I try to logon with any of the accounts in there it fails. when i create a new account it is successfully created but it doesnt show up in the accountDB database. All the new accounts i have created are working find but i dont know or should i say cant fine them anywhere on my system. I need help people!!!

**Comment by kahanu** [comment]
You need to check the connection string that is set in your membership providers sections.  That's where the accounts Db is.

Sent from my Windows Phone

**Comment by howardrhyne** [comment]
I have the same issue.  Here is my connection string:

```
<add name="DefaultConnection" connectionString="Server=HLR;Database=reality;Trusted_Connection=True;" providerName="System.Data.SqlClient" />
```

**Comment by kahanu** [comment]
@howardrhyne - the connectionstring works better this was for SQL Server 2008 or higher.

```
<add name="DefaultConnection" connectionString="Data Source=localhost\sqlserver2008;Initial Catalog=MyDatabase;Integrated Security=True" providerName="System.Data.SqlClient" />
```
