### ISSUE TITLE
links to user details under Users in Role in  /SecurityGuard/Role don't work

### ISSUE THREAD

**Issue by dkitchen** [kahanu/Security-Guard#17]
I had some problems with bad user-links below "Users In Role" in /SecurityGuard/Role

I think this is because I'm using a virtual directory.

I changed line 223 in \Areas\SecurityGuard\Views\Role\Index.cshtml from:

```
ul.append("<li><a href=\"/SecurityGuard/Membership/Update/" + item + "\">" + item + "</a></li>");
```

to:

```
ul.append("<li><a href=\"Membership/Update/" + item + "\">" + item + "</a></li>");
```

Not sure if this will work in all cases but hope that helps.

**Comment by kahanu** [comment]
@dkitchen - your fix will be fine for your virtual application.  I think I remember needing this fully qualified reference because of namespace collisions, but in your case it shouldn't pose a problem.
