### ISSUE TITLE
Posting to SGAccount LogOff results in 404

### ISSUE THREAD

**Issue by dkitchen** [kahanu/Security-Guard#18]
LogOff works fine when requested via GET, but throws a 404 on POST.

To fix this I changed \Controllers\SGAccountController.cs line 102 from:

```
[HttpGet]
public virtual ActionResult LogOff()
```

to:

```
[AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
public virtual ActionResult LogOff()
```

I hope that helps.

**Comment by kahanu** [comment]
@dkitchen - I assume you are issuing a POST when using the LogOn popup?  Your solution is probably the appropriate one.  I'll update my code shortly.  Thanks.

**Comment by kahanu** [comment]
I just updated the code to contain this fix.  Thanks for the heads up.
