### ISSUE TITLE
Any chance of updating to work with MVC 4?

### ISSUE THREAD

**Issue by rbanks54** [kahanu/Security-Guard#2]
Subject says it all

**Comment by kahanu** [comment]
Richard, yes, as soon as I have a moment.  I'm kind of swamped with paying jobs, but I do plan on getting to it.

King

**Comment by leniel** [comment]
Richard,

I'm using it with MVC 4.

Until now I had to make these 2 modifications to make it work:

1 - Add a new dependent assembly binding redirect in the MVC 4 app Web.config as per this answer at StackOverflow http://stackoverflow.com/a/10556822/114029:

```
 <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages.Razor"
           publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="2.0.0.0"/>
 </dependentAssembly>
```

2 - Change @Html.TextBox("searchterm", Model.SearchTerm, null) to @Html.TextBox("searchterm", Model.SearchTerm, null, null) inside \Areas\SecurityGuard\Views\Membership\Index.cshtml

Hope it helps.

**Comment by kahanu** [comment]
Thanks leniel for looking into this.  I literally have not had time to dedicate to this with my present workload.  I'll try to give it some time this weekend, but I haven't even had time to check out the MVC 4 bits yet.  :^(  

I'm glad you found a fix in the meantime.

**Comment by kahanu** [comment]
Richard and Leniel, I just wanted you to know that I've made a SecurityGuard.MVC4 NuGet package.  With Leniel's help I was able to make this new version quickly and easily.  If you try in in your MVC 4 application, post any issues you may have.  Thanks.
