### ISSUE TITLE
Manage View missing

### ISSUE THREAD

**Issue by acastaner** [kahanu/Security-Guard#20]
Just installed the version 1.0.8 from NuGet (Package-Install SecurityGuard.MVC4), and the Manage views (both aspx and cshtml) seem to be missing from the "Views/SGAccount" directory.

This obviously trigger errors are there are references to that View (notably in _LoginPartial.cshtml).
![2012-12-21 14_21_51-HomeNetworking - Microsoft Visual Studio Express 2012 for Web](https://f.cloud.github.com/assets/2143819/27108/a7c4a688-4b71-11e2-8160-b20bd7717fb9.png)

**Comment by kahanu** [comment]
@Dwobin - Hi, are the views you are showing me from a previous install or the one you are having a problem with?  If they are in fact missing, you can try to uninstall the SecurityGuard package and reinstall it.  The views are they and do show up.  Something may have occurred in this NuGet installation that prevented them from installing. Give that a try.

Once they do appear, don't forget to delete the set that you aren't using in your application.

Thanks.

**Comment by acastaner** [comment]
@kahanu I've done it again, and I can confirm that the "Manage" view is the only one missing.

**Comment by acastaner** [comment]
Note that I get this error when installing from the console:

Successfully installed 'EntityFramework 5.0.0'.
Successfully installed 'T4Scaffolding 1.0.8'.
Successfully installed 'MvcMailer 4.0'.
Successfully installed 'SecurityGuard.MVC4 1.0.8'.
Successfully added 'T4Scaffolding.Core 1.0.0' to HomeNetworking.
Successfully added 'EntityFramework 5.0.0' to HomeNetworking.

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Successfully added 'T4Scaffolding 1.0.8' to HomeNetworking.
Successfully added 'MvcMailer 4.0' to HomeNetworking.
Exception calling "EnumerateFiles" with "3" argument(s): "The path is not of a legal form."
At E:\Documents\GitHub\Honewe-cloud\packages\MvcMailer.4.0\tools\Install.ps1:8 char:45
-         | %{ [System.IO.Directory]::EnumerateFiles <<<< ($_, "*." + $extension, [System.IO.SearchOption]::AllDirectories) }
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : DotNetMethodException

Exception calling "EnumerateFiles" with "3" argument(s): "The path is not of a legal form."
At E:\Documents\GitHub\Honewe-cloud\packages\MvcMailer.4.0\tools\Install.ps1:8 char:45
-         | %{ [System.IO.Directory]::EnumerateFiles <<<< ($_, "*." + $extension, [System.IO.SearchOption]::AllDirectories) }
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : DotNetMethodException

**Comment by kahanu** [comment]
@Dwobin - I've tested this many times and it's installed everything correctly.  Can you tell me specifics about your installation?  OS, VS version, .Net framework version, etc.

Another thing you can try is to run Visual Studio as Administrator and then try to install the package.

Regarding the Manage view, this is not part of SecurityGuard. This view is a default view installed by VS when you create a new package.  You are probably seeing this when you log in and then click on the username.  This view allows you to manage things like Changing your Password.  Unless you need ALL of these operations, I would change the _LoginPartial.cshtml to remove the link around the username to the Manage view and just create your own link for users to change their password.  SecurityGuard handles most of the other operations anyway.

I hope this helps.

**Comment by subai** [comment]
Hi acastaner
I'm wondering how you managed to fix the "Manage" thing, it won't show up what ever I do
there is only one "Manage" in Account not SGAcount

**Comment by kahanu** [comment]
@acastaner - I don't use it.  It's part of the default MVC template, not something I use in SecurityGuard.  But I cover everything that it does in the SecurityGuard Dashboard, so there's no need for it.  Just ignore it.  Look at the MVC Central article on it, http://www.mvccentral.net/s/43, and you'll see how you can create your Login links to disregard it.  I hope this helps.

**Comment by subai** [comment]
Hi King
I think my comment was not very clear and helpful sorry about that , I have the same problem as acastaner, I did things you kindly explained in that article many times in diffrent situations, but there is no Action/View as "Manage" in SGAcount (I tried run as administrator, Installing using command, installling using Nuget manager UI,using other starter templates,...)
BTW I'm trying to build a MVC4 App in VS2012 on Win7 using internet template

I think there should be a small mistake or misunderstanding for me because this topic is closed and no one else has this problem,
if posible can you attach a mvc4 empty solution with Security Guard pakage installed, pls

Thx

**Comment by kahanu** [comment]
@subai - sorry my mistake, yes there is no "Manage" command in SGAccount Controller by design.  It is something that is only built into the default MVC template in Visual Studio, so I don't use it. There is no need since I cover all the membership needs in the SecurityGuard Area.

Can you tell me what problems you are having?  I'm not clear on what issues you are having.

**Comment by acastaner** [comment]
Since it's a default link, maybe add an action that simply redirects to the right page?

**Comment by subai** [comment]
Thanks for the replys
I'm new to MVC and this is the line that I don't undestand
Hello, @Html.ActionLink(User.Identity.Name, "Manage", "SGAccount", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })

I think it's refering to an Action Named "Manege" in the SGAccount Controller, so I'm confused
I'd be very happy if you point out what's my problem,
