### ISSUE TITLE
Using EntityFramework 5.0 is not supported for Security-Guard

### ISSUE THREAD

**Issue by maurodx** [kahanu/Security-Guard#21]
I have installed latest NuGet package from SecurityGuard but when I try to register a user I get an exception regarding missing EntityFramework 4.4 assembly

**Comment by kahanu** [comment]
@maurodx - The EntityFramework 5.0 version is only available for applications built with the .Net 4.5 Framework, so you would need to be building an ASP.NET MVC 4 application in Visual Studio 2012 using the .Net 4.5 Framework.  Then you would select the SecurityGuard.Mvc4 NuGet package.  I hope this helps.

**Comment by maurodx** [comment]
Yes sorry, the problem wasn't SecurityGuard but the provider under it. Solved!
