### ISSUE TITLE
MembershipService.GetAllUsers parameterless overload should return all users

### ISSUE THREAD

**Issue by nrkn** [kahanu/Security-Guard#22]
Currently it returns 20:

```
public System.Web.Security.MembershipUserCollection GetAllUsers()
{
    int totalRecords;
    return membershipProvider.GetAllUsers(0, 20, out totalRecords);
}
```

**Comment by kahanu** [comment]
Where do you see this?  This is not in the code any longer.  The latest code returns all relevant records.

**Comment by nrkn** [comment]
https://github.com/kahanu/Security-Guard/blob/master/SecurityGuard/Services/MembershipService.cs#L153

We're working around it by doing this:

```
var totalRecords = 0;
membershipService.GetAllUsers(0, 1, out totalRecords);
var users = membershipService.GetAllUsers(0, totalRecords, out totalRecords);
```

But I thought you might like to know anyway :)

**Comment by kahanu** [comment]
The latest is in the NuGet package.

Mvc4/NuGet/content/Areas/SecurityGuard/Controllers/MembershipController.cs.pp

**Comment by nrkn** [comment]
Awesome. Thank you.

**Comment by nrkn** [comment]
Actually, latest version from NuGet,  the code is still set to retrieve the first 20 only.

**Comment by nrkn** [comment]
Decompiled from DLL in newest NuGet package:

```
    public MembershipUserCollection GetAllUsers()
    {
      int totalRecords;
      return this.membershipProvider.GetAllUsers(0, 20, out totalRecords);
    }
```

**Comment by kahanu** [comment]
There is an overload of this method.

```
public System.Web.Security.MembershipUserCollection GetAllUsers(int pageIndex, int pageSize, out int totalRecords)
{
    return membershipProvider.GetAllUsers(pageIndex, pageSize, out totalRecords);
}
```

**Comment by kahanu** [comment]
https://github.com/kahanu/Security-Guard/blob/master/SecurityGuard/Services/MembershipService.cs

Line 159

I hope this helps.
