### ISSUE TITLE
Problem Navigating Users with special characters in

### ISSUE THREAD

**Issue by NoseBagUK** [kahanu/Security-Guard#23]
When navigating between users it doesn't work if the user has a full stop (period) in the user name, because you cant put them in the url string...

/SecurityGuard/Membership/Update/phil.hey

Maybe it would be better to post the username.

**Comment by kahanu** [comment]
@PhiliciousUK - I'm not sure what problems you are having, but I can update a user with a period in it without a problem.  How old is your version of SecurityGuard?

**Comment by aldari** [comment]
I have a version .54.586
You do not use HtmlEncode/HtmlDecode for user name in url. It is not possible to watch a detail of user with name for example, some@host.com.  Symbol @  have to be escaped.

**Comment by kahanu** [comment]
@aldari - I'm not sure I understand what you mean by "watch a detail", but @ symbols work fine.  Are you getting errors?  What problems are you having and where are they occurring?

**Comment by aldari** [comment]
UserCase: 1) user registers an account with his mail hell--00@mail.ru in UserName field.
2) I can't to visit a page with url like http://_host_/SecurityGuard/Membership/Update/hell--00%40mail.ru
I got a 404 not found page.
A '@' symbol is restricted and it has encoded. Later In a controller Membership a string(hell--00%40mail.ru) would decoded to hell--00@mail.ru before quering a user. 
The second solution is to restrict usernames which looks like email.
