### ISSUE TITLE
Javascript problem in SecurityGuard-MVC. when using IE 10

### ISSUE THREAD

**Issue by yobiwoo** [kahanu/Security-Guard#24]
Hi Kahanu,
I having error when i click Create User.

Unhandled exception at line 16, column 28705 in http://localhost:54793/Content/SecurityGuard/scripts/jquery-1.6.1.min.js

0x80020003 - JavaScript runtime error: Member not found. 

Only happen for IE 10 and google Chrome working fine. Hope you can guide me.Thanks

**Comment by kahanu** [comment]
I have not tested this in IE 10, but in the meantime you should be able to just upgrade jQuery and it should work.  Give that a try.

**Comment by yobiwoo** [comment]
thank you for your reply. I have tested with latest jQuery but still having same problem as below

Unhandled exception at line 2, column 32075 in http://localhost:54793/Content/SecurityGuard/scripts/jquery-1.8.2.min.js

0x80020003 - JavaScript runtime error: Member not found.

**Comment by kahanu** [comment]
Where, in SecurityGuard, are you getting this error?  On what page and what command?

**Comment by kahanu** [comment]
I just tested this in IE 10 and I didn't get any error when I created a new user.  I'm on a Windows 7 system.  What system are you on?  Windows or Mac?

**Comment by yobiwoo** [comment]
I'm using windows 7 also.maybe my system having prob..thanks for help.

**Comment by soslan2002** [comment]
Tested in Windows 7 + IE10 and everything is ok.

**Comment by soslan2002** [comment]
By the way, kanahu, thank you very much for your contribution.
