### ISSUE TITLE
SG create SQLExpressDatabase

### ISSUE THREAD

**Issue by hamed-kh** [kahanu/Security-Guard#25]
Dear kahanu
i used the security guard in my mvc3 application
it works good in my vs2010 , after i published the application and try to test in my iss i understand that when i want to view security guard area in my website it tries to ceate a sqlexpress database , i checked my project and see the App_Data foldr with a ASPNETDB.MDF named file,i copied this file in my iss and the website works fine!
now i upload this application to a windows server 2008 R2 host and an error occur,this error is about the sqlExpress, i want to know is there any way to force SG not to create SQLexpress database ?
the error is this : "Failed to generate a user instance of SQL Server due to failure in retrieving the user's local application data path. Please make sure the user has a local user profile on the computer. The connection will be closed. 
"
my connection string works fine and sets to the correct database
thank you
Best regards

**Comment by kahanu** [comment]
Hi,

SecurityGuard simply works off of the connection string.  If it's set to SqlExpress then that's where the database will be created.

You need to enter the connection string  to the database that you want it to work with.

Its all up to you.

Sent from my Windows Phone

**Comment by hamed-kh** [comment]
Dear Kahanu
i checked the projects you uploaded and see i forgot "profile provider" and "role manager provider" in my web.config
i add these 2 and the site works fine
thank you for your quick answer
Best regards
