### ISSUE TITLE
library script loading

### ISSUE THREAD

**Issue by GuyKroizman** [kahanu/Security-Guard#28]
In SG view jquery is loaded like this:
`<script src="@Url.Content("~/Content/SecurityGuard/scripts/jquery.validate.min.js")" type="text/javascript"></script>`

but the views created by new mvc 4 internet template use:
`@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}`

Would it be better to use the second form?

**Comment by kahanu** [comment]
@GuyKroizman - unless you think your SecurityGuard Area will get lots of traffic, I would leave it.  Bundles require more manual settings than can be offered easily with NuGet, so I didn't use that method, but you can create a bundle for it if you want.  There's nothing wrong with doing that.

**Comment by GuyKroizman** [comment]
Got it, thanks!
