### ISSUE TITLE
Change Password 

### ISSUE THREAD

**Issue by GuyKroizman** [kahanu/Security-Guard#29]
Hi
I believe the Change Password link is missing. One can find it using /SGAccount/ChangePassword but maybe there should a page that manage user details and lets her change the password...

**Comment by kahanu** [comment]
@GuyKroizman - sorry about being so late on this, I don't know how I missed it.  

For your member site, you need to provide the proper place for a member to change their password.  There is no universal placement for this, so I cannot build this into SecurityGuard upon installation.  It's something that is custom to your application that you configure in your _Layout.cshtml view.

I hope this helps.
