### ISSUE TITLE
'System.Data.Objects.ObjectContext  error on installing membership tables using mvcinstaller.mvc4

### ISSUE THREAD

**Issue by Taspiya** [kahanu/Security-Guard#32]
Getting following error when running mvcinstaller.mvc4 
Error creating roles, 'System.Data.Objects.ObjectContext System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()'

**Comment by kahanu** [comment]
@Taspiya - This is the SecurityGuard Issues area, not MvcInstaller.  Can you repost in MvcInstaller Issues?
