### ISSUE TITLE
Navigating to a user page with special @ character

### ISSUE THREAD

**Issue by aldari** [kahanu/Security-Guard#33]
UserCase: 1) user registers an account with his mail hell--00@mail.ru in UserName field.
2) I can't to visit a page with url like http://host/SecurityGuard/Membership/Update/hell--00%40mail.ru
I got a 404 not found page.
A '@' symbol is restricted and it has encoded. Later In a controller 'Membership' a string(hell--00%40mail.ru) would decoded to hell--00@mail.net before quering a user.
The second solution is to restrict usernames which looks like email at all.

**Comment by kahanu** [comment]
@aldari - Hi, I'm not able to reproduce this issue.  This has been submitted before by some people, but I've tested this with many browsers and I have never had any issues or problems.  Can you tell me more about your application and browser version?
