### ISSUE TITLE
_LogOnPartial error

### ISSUE THREAD

**Issue by DovFel** [kahanu/Security-Guard#34]
i am using mvc4 in vs2010
when i use this line in my  
 Hello, @Html.ActionLink(User.Identity.Name, "Manage", "SGAccount", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })!
i got error when i select the link .
i change to this line 
 Hello, @Html.ActionLink(User.Identity.Name, "Update", "Membership", routeValues: new { area = "SecurityGuard" , userName = User.Identity.Name },  htmlAttributes: new { @class = "username", title = "Manage" })!
and it is work 
way?

**Comment by kahanu** [comment]
@DovFel - your issue with the "Manage" link is explained in the MVC Central article.  http://www.mvccentral.net/s/43 

The Manage link is not used by SecurityGuard.  This is part of the standard MVC Visual Studio template used when you create a new MVC project, so this is not a bug, but a feature by design.  I hope this helps.

**Comment by DovFel** [comment]
looking  at article. http://www.mvccentral.net/s/43 i sow that  you ask to adding this line 
on the section "LoginPartial Updates" the title is "Now you'll need to make a few little changes.  The first you'll make is to the _LoginPartial.cshtml view.  You will change the controller names to point to the new SecurityGuard Account controller."
Hello, @Html.ActionLink(User.Identity.Name, "Manage", "SGAccount", routeValues: null, htmlAttributes: new { @class = "username", title = "Manage" })!
And it's not a link created in creating a new project

**Comment by kahanu** [comment]
@DovFel - my apologies, that code is wrong.  I shouldn't have included the Manage action since it's not used in SecurityGuard.  Just remove that ActionLink for Manage.
