### ISSUE TITLE
i cant see dashboard view

### ISSUE THREAD

**Issue by sulopez** [kahanu/Security-Guard#35]
hi! i did the tutorial of security guard mvc4 for VS 2012, and I cant see de dashboard view.. besides I can't access to role manager...

**Comment by kahanu** [comment]
I'm sorry you are having problems.  To access the SecurityGuard Dashboard, you need to be in the SecurityGuard role.  If you did not use MvcInstaller to set up the Membership system, then you'll need to use the WSAT (Website Administration Tool) in Visual Studio to create that role.  Then you'll need to add the user that will have access to SecurityGuard to that role.  Then it will all work.

**Comment by sulopez** [comment]
actually I'm using security guard.. I can register, logIn and logOut.. but I can't access to the dashboard window.. 

also doing a review, I'm seeing that in the installer tutorial I could'nt access to the install part  (in the browser) and watch the roles created and add the other role and all that...

thanks...

**Comment by kahanu** [comment]
@sulopez - the fact that you can register, login and out using SecurityGuard does not also give you access to the SecurityGuard Dashboard.  Again, for that you need to have an administrator user in the role of SecurityGuard.  My article on MvcCentral points this out under the "Ready To Go" heading.  http://www.mvccentral.net/s/43

Regarding MvcInstaller (if that's what you used) and you can't access the /Install path in the browser, create a new permission in the web.config to allow access.

```
    <location path="install">
        <system.web>
            <authorization>
                <allow users="*" />
            </authorization>
        </system.web>
    </location>
```
