### ISSUE TITLE
Use MVCMailer to send e-mails using MVC views

### ISSUE THREAD

**Issue by leniel** [kahanu/Security-Guard#4]
MVC Mailer https://github.com/smsohan/MvcMailer/ is a much better approach to send e-mails and it could be easily integrated in this project! :)

> vcMailer provides you with an ActionMailer style email sending NuGet Package for ASP.Net MVC 3. So, you can produce professional looking emails composed of your MVC master pages and views with ViewBag.

**Comment by kahanu** [comment]
Yes, I've used MvcMailer in other applications. It rocks!  I may integrate it into SecurityGuard at some point.  I used my own email component for this.  I don't think MvcMailer was available when I first created SecurityGuard.
