### ISSUE TITLE
Application Management

### ISSUE THREAD

**Issue by jlsfernandez** [kahanu/Security-Guard#6]
Hi one of the best things of this kind of Wrappers around the membership technology will be if can be managed also the applications, i mean could create applications, but most important can users be associated with applications to be able to manage a central repository as asp.net membership from this project.

Thanks

**Comment by kahanu** [comment]
@jlsfernandez I'm not sure I completely understand what you are asking.  If you are wondering if there's a way of creating and managing the applications for the Membership system, I have never thought of that.  Off the top of my head I don't know if there's a built-in way of doing this, but I'm sure a simple set of functions could be created to enable this.

If you wanted to add a named application to the Membership system when it is created that isn't the default "/", you can easily do that with my other NuGet pacakge called MvcInstaller.  Check out that github repository and I also have videos on it, in www.mvccentral.net/tools. 

I hope this helps.

**Comment by kahanu** [comment]
Sorry the link is, http://www.mvccentral.net/Story/Search/tools.
