### ISSUE TITLE
Total user count on Dashboard is incorrect

### ISSUE THREAD

**Issue by SteveHiner** [kahanu/Security-Guard#7]
I noticed that the dashboard showed 20 users total for my site and there are a lot more than that. I changed the existing code in DashboardController's Index action from:
            viewModel.TotalUserCount = membershipService.GetAllUsers().Count.ToString();

and replaced it with:
            int total;
            membershipService.GetAllUsers(0, 1, out total);
            viewModel.TotalUserCount = total.ToString();

Now it shows over 300 users as it should.  I didn't try to dig into why the parameterless version doesn't return the right number.

**Comment by kahanu** [comment]
Steve, I'll take a look at it this weekend.  Thanks for the catch.  King Wilder

**Comment by SteveHiner** [comment]
While I have your attention...

Thank you for writing Security Guard and for releasing it for us to use.
It's great and it saved me a ton of time.

I do wish I could modify the visual appearance without losing the ability
to upgrade the package via NuGet.  Last time I tried an upgrade it really
messed up the SG install and I had to roll it back in SVN.  I might try
pulling the new version into another project and then use WinMerge to
compare the changes to try to manually upgrade my version.  I was trying to
make it look more like the rest of the site which is using the standard
MVC3 tabbed layout.

I look forward to trying out the new MVC4 capable version in a site I'm
building for my brother.

Steve

On Thu, Jun 28, 2012 at 5:45 PM, King Wilder <
reply@reply.github.com

**Comment by kahanu** [comment]
Steve, regarding updating the appearance and saving the configuration for upgrades... this IS an issue I'm trying to solve so that it's easy to modify for your look and feel, but will keep it when you upgrade.  Unfortunately my time, lately, is limited to concentrate on this, but I have not abandoned it.

I'll update this notice when I've got something working.

King Wilder

**Comment by SteveHiner** [comment]
Cool, I still love it, I'll still use it, I'll still recommend it.  I
totally understand how limited time can be on stuff like this.  I have
numerous side projects that could really use my attention.

Steve

On Mon, Jul 2, 2012 at 3:25 PM, King Wilder <
reply@reply.github.com

**Comment by kahanu** [comment]
I've updated the Total count to reflect the total number of users correctly.
