### ISSUE TITLE
Ambiguous CompareAttribute in Security Guard 1.0.3

### ISSUE THREAD

**Issue by aknuds1** [kahanu/Security-Guard#8]
I'm experiencing one compilation issue with Security Guard 1.0.3, after having installed it into my ASP.NET MVC 4 (RC) project via NuGet. In ChangePasswordViewModel.cs and RegisterViewModel.cs, the `CompareAttribute` references are ambiguous since they can be resolved to either `System.ComponentModel.DataAnnotations` or `System.Web.Mvc`. I take it the intended namespace is `System.Web.Mvc`?

**Comment by kahanu** [comment]
@Arve - I've never had an issue with this, but yes it would be System.Web.Mvc namespace.  I'll update the code.  Thanks for pointing this out.
