### ISSUE TITLE
SecurityGuard.MVC4 1.0.3 - Trouble with removing yourself from the administrator role

### ISSUE THREAD

**Issue by aknuds1** [kahanu/Security-Guard#9]
I'm using SecurityGuard.MVC4 1.0.3 in combination with ASP.NET MVC 4. As a test, I logged in as admin and via the Security Guard dashboard I removed myself from the 'Administrator' role (having renamed the 'SecurityGuard' role to this), before I then tried to re-grant the role to myself. This led to an error in Security Guard, where I was prompted with a dialog notifying me of a syntax error: '<'. So I refreshed the page, and I was no longer in the Administrator role, and correspondingly I was denied access to the Security Guard dashboard.

Do you think there should be some sane way of handling this scenario in Security Guard? For instance, deny removing the last administrative user (in whichever role authorizes access to Security Guard) or ask for confirmation that you're sure you wish to remove yourself from the role in question?

**Comment by kahanu** [comment]
@aknuds1 - I never thought of adding that type of feature, but yes it could be added I guess.  I'm not sure why anyone would remove themselves as an Administrator since that's the role you need to log in with.  And if I understand you correctly, that you renamed the SecurityGuard role to Adminstrator, that won't work.  The controllers for the SecurityGuard Area all need that role for Authorization.

**Comment by aknuds1** [comment]
Well, it's good to handle this scenario at least. It could happen by mistake for instance. Renaming the SecurityGuard role worked for me, since I tweaked the SecurityGuard controllers etc.

**Comment by kahanu** [comment]
@aknuds1 - it's actually better if you don't rename the role from SecurityGuard to something else.  The SecurityGuard Dashboard should ONLY be accessible to an authorized user, and that user will be the one who is in the role of SecurityGuard.  There could be many Administrators to the overall web application, but there should only be one (or maybe two) SecurityGuard roles.  By limiting the number of users who are assigned to this role, limits the possibility of the Membership system becoming compromised.
